# Generated by Django 4.2.1 on 2023-12-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0002_invoiceitem_customuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
