# Generated by Django 4.2.1 on 2023-12-03 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0004_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='transaction_method',
            new_name='payment_mode',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='purchase_date',
            new_name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='account',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='account',
            name='reference_number',
        ),
    ]
