# Generated by Django 4.2.1 on 2023-12-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0007_rename_is_creadit_account_is_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_debit',
        ),
    ]
