# Generated by Django 4.2.1 on 2023-12-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0008_remove_account_is_debit'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
