# Generated by Django 4.2.1 on 2023-12-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0010_alter_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
