# Generated by Django 4.2.1 on 2023-12-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0011_alter_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
