# Generated by Django 4.2.1 on 2023-12-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0012_alter_account_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_added_in_account',
            field=models.BooleanField(default=False),
        ),
    ]
