# Generated by Django 4.2.1 on 2023-12-09 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0013_invoice_is_added_in_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='PerformaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performa_invoice_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('party_name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('mobile', models.CharField(max_length=12)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Developer.state')),
            ],
        ),
    ]
