# Generated by Django 4.2.1 on 2023-12-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0015_performainvoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='performainvoiceitem',
            name='gst_amount',
            field=models.IntegerField(null=True),
        ),
    ]
