# Generated by Django 4.2.1 on 2023-12-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0017_performainvoiceitem_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='transaction_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
