# Generated by Django 4.2.1 on 2023-12-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0018_account_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='payment_mode',
            field=models.CharField(choices=[('Phone Pay', 'Phone Pay'), ('Credit Card', 'Credit Card'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Cheque', 'Cheque')], max_length=50),
        ),
    ]
