# Generated by Django 4.2.1 on 2023-12-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0019_product_minimum_stock_alter_account_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='transaction_date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
