# Generated by Django 4.2.1 on 2024-02-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0021_alter_account_transaction_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='packing_charges',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='transportation_charges',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
