# Generated by Django 4.2.1 on 2024-02-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0022_invoice_packing_charges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
