# Generated by Django 4.2.1 on 2024-02-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0023_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_original',
            field=models.BooleanField(default=True),
        ),
    ]
